//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnatidaeHaxball
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AHDBEntities : DbContext
    {
        public AHDBEntities()
            : base("name=AHDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrador> Administrador { get; set; }
        public DbSet<Competicao> Competicao { get; set; }
        public DbSet<Equipa> Equipa { get; set; }
        public DbSet<Estatistica> Estatistica { get; set; }
        public DbSet<Jogador> Jogador { get; set; }
        public DbSet<Jogo> Jogo { get; set; }
    }
}
