//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnatidaeHaxball
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipa
    {
        public Equipa()
        {
            this.Jogo2 = new HashSet<Jogo>();
            this.Jogo11 = new HashSet<Jogo>();
        }
    
        public int idEquipa { get; set; }
        public string tag { get; set; }
        public string nome { get; set; }
        public bool activa { get; set; }
        public string logo { get; set; }
    
        public virtual ICollection<Jogo> Jogo2 { get; set; }
        public virtual ICollection<Jogo> Jogo11 { get; set; }
    }
}
