//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnatidaeHaxball
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estatistica
    {
        public int jogoId { get; set; }
        public int competicaoId { get; set; }
        public int jogadorID { get; set; }
        public Nullable<int> golos { get; set; }
        public Nullable<int> assistencias { get; set; }
    
        public virtual Jogador Jogador { get; set; }
        public virtual Jogo Jogo { get; set; }
    }
}
