//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnatidaeHaxball
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogador
    {
        public Jogador()
        {
            this.Estatistica = new HashSet<Estatistica>();
            this.LogJogadores = new HashSet<LogJogadores>();
        }
    
        public int idJogador { get; set; }
        public string nome { get; set; }
        public string avatar { get; set; }
        public string posicao { get; set; }
        public bool naEquipa { get; set; }
        public string nomeShirt { get; set; }
        public string ave { get; set; }
    
        public virtual ICollection<Estatistica> Estatistica { get; set; }
        public virtual ICollection<LogJogadores> LogJogadores { get; set; }
    }
}
